management:
  info:
    build:
      enabled: true
    git:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
server:
  port: 8686
spring:
  data:
    mongodb:
      host: 192.168.0.140
      port: 27017
      database: dilemma
data:
  elasticsearch:
    host: 192.168.0.34
    port: 9200
    username: admin
    password: YourPassword