package org.pds.security.google2fa;

/**
 * TOTP (Time-based One-Time Password algorithm),
 * extension of the HOTP (HMAC-based One-time Password) algorithm,
 * generate a one-time password by instead taking uniqueness from the current time
 */
public interface TOTP {

    /**
     * @param step - 30 seconds StepSize (ID TOTP)
     * @param key - secret credential key (HEX)
     * @return 6-digits one-time password (OTP) generated by the TOTP algorithm
     */
    public String getOTP(final long step, String key);

}
